name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - llvm16
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]
        arch: [x86_64, aarch64]
    timeout-minutes: 420
    runs-on: [self-hosted, Linux, "${{ matrix.arch }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: sh ci/${{ matrix.arch }}-linux-${{ matrix.type }}.sh
  x86_64-macos-release:
    runs-on: "macos-11"
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/x86_64-macos-release.sh
  aarch64-macos-debug:
    runs-on: [self-hosted, macOS, aarch64]
    env:
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/aarch64-macos-debug.sh
  aarch64-macos-release:
    runs-on: [self-hosted, macOS, aarch64]
    env:
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/aarch64-macos-release.sh
  x86_64-windows-debug:
    runs-on: windows-latest
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/x86_64-windows-debug.ps1
  x86_64-windows-release:
    runs-on: windows-latest
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/x86_64-windows-release.ps1
  aarch64-windows:
    runs-on: [self-hosted, Windows, aarch64]
    env:
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/aarch64-windows.ps1
